name: Test 1C Server on Multiple Platform Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        onec_version:
          - '8.3.22.2557'
          - '8.3.24.1548'
          - '8.3.25.1445'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image for version ${{ matrix.onec_version }}
      run: docker build --build-arg ONEC_VERSION=${{ matrix.onec_version }} -t onec-server:${{ matrix.onec_version }} .

    - name: Run Docker container in dry-run mode for version ${{ matrix.onec_version }}
      env:
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      run: |
        docker run --rm --name onec-server-test-${{ matrix.onec_version }} \
          -e ONEC_USERNAME \
          -e ONEC_PASSWORD \
          -e ONEC_VERSION=${{ matrix.onec_version }} \
          onec-server:${{ matrix.onec_version }} dry-run

    - name: Show container logs for version ${{ matrix.onec_version }}
      if: failure()
      run: docker logs onec-server-test-${{ matrix.onec_version }}
